# Git Alias
alias catt="git commit -a -m "
alias gpom="git push origin main"
alias gpod="git push origin development"
alias gpos="git push origin stable"
alias gpomt="git push origin main --tags"
alias gpoma="git push origin master"
alias gpol="git push origin live"
alias gpop="git push origin production"
alias gpob="git push origin buildout"
alias gpo="git push origin"
alias gpot="git push origin --tags"
alias gs="git status"
alias gg="ghq get"